# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-30 03:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_line_1',
            field=models.CharField(max_length=200, verbose_name='Adres 1'),
        ),
        migrations.AlterField(
            model_name='address',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Adres 2'),
        ),
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('fatura', 'Fatura'), ('kargo', 'Kargo')], max_length=120, verbose_name='Adres Tipi'),
        ),
        migrations.AlterField(
            model_name='address',
            name='billing_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.BiliingProfile', verbose_name='Faturalama profili'),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(default='Izmir', max_length=120, verbose_name='Şehir'),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(default='Turkiye', max_length=120, verbose_name='Ülke'),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(max_length=120, verbose_name='İlçe'),
        ),
    ]
