# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-03 01:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20181203_0345'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Kullanıcı Adı'),
        ),
    ]
