# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-16 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='', max_length=120),
        ),
    ]
